nats:
  jetstream:
    enabled: false

auth:
  enabled: true
  basic:
    accounts:
      USERS:
        users:
        - user: a
          password: a
      SYS: 
        users:
        - user: admin
          password: changeit
  systemAccount: SYS

cluster:
  enabled: true
  replicas: 3
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

gateway:
  enabled: true
  name: "kind-3"
  gateways:
  - name: "kind-1"
    urls:
    - "nats://nats-0.nats.default.svc.kind-1.form3.local:7522"

k8sClusterDomain: kind-3.form3.local